<?php
namespace OC\PlatformBundle\Entity;
use Doctrine\ORM\EntityRepository;
// N'oubliez pas ce use
use Doctrine\ORM\QueryBuilder;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
    public function getApplicationsWithAdvert($limit){
        
        $qb = $this
	->createQueryBuilder('a')
	->innerJoin('a.advert', 'adv')
	->addSelect('adv')
        ->setMaxResults( $limit )
	;

	return $qb
	->getQuery()
	->getResult()
	;
        
    }
}
